# Pauli Matrices

In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [10]:
sx=np.array([[0,1],[1,0]])
ex=np.linalg.eig(sx)

sy=np.array([[0,-1j],[1j,0]])
ey=np.linalg.eig(sy)

sz=np.array([[1,0],[0,-1]])
ez=np.linalg.eig(sz)

In [13]:
ex,ey,ez

((array([ 1., -1.]),
  array([[ 0.70710678, -0.70710678],
         [ 0.70710678,  0.70710678]])),
 (array([ 1.+0.j, -1.+0.j]),
  array([[-0.        -0.70710678j,  0.70710678+0.j        ],
         [ 0.70710678+0.j        ,  0.        -0.70710678j]])),
 (array([ 1., -1.]),
  array([[1., 0.],
         [0., 1.]])))

# Normal mode

In [14]:
a=np.array([[2,-1],[-1,2]])
a

array([[ 2, -1],
       [-1,  2]])

In [15]:
ea=np.linalg.eig(a)
ea

(array([3., 1.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

###### 직교성분이 내적했을때  0이므로, 고유벡터 a의 성분 a_ij는 직교조건으로 부터 계산할수 있다. 
###### 표준좌표로 보았을 때 w1은 같은 위상을 가지며, w2는 역위상을 같게 된다.